#!/usr/bin/env python3
"""Create the Zava **Fabric Data Agent (GA)** — idempotently and as code (plan Step 17;
R3 §4 / R4 §5.3). The *"insights beyond Power BI"* pillar: natural-language Q&A over
Zava's governed data via the **Fabric Data Agent REST API**.

What it does
------------
1. Resolves all identifiers from ``deploy_config.json`` (Step 1 schema): the target
   workspace (``workspace.use_existing`` / ``workspace.existing_workspace_id`` /
   ``workspace.name``, created by Step 10), the **Step-14 Direct Lake semantic model**
   (``semantic_model.name`` -> default ``Zava Fleet Analytics``) and the **Step-16
   ontology's auto-created Graph** (``ontology.name`` -> default ``ZavaFleetOntology``;
   the managed Graph is resolved by ``data_agent.graph_name`` or by the single ``Graph``
   item in the workspace). Honours the ``features.enable_data_agent`` gate (default
   ``true``). The **graph source** is included only when ``features.enable_ontology=true``
   AND a Graph item is resolvable. CLI / environment overrides take precedence.
   **No secrets are read from config.**
2. Authenticates via ``DefaultAzureCredential`` (``az login`` / managed identity /
   env service principal), falling back to the Azure CLI
   (``az account get-access-token``) when ``azure-identity`` is absent. A single
   audience is used: the Fabric control plane (``https://api.fabric.microsoft.com``).
3. **Resolves the live artifact ids** of the Step-14 semantic model and the Step-16
   ontology's auto-created Graph (R3 line 358: retrieve real ids via the Fabric REST API
   before assembling the definition) so the data-source bindings point at real items.
4. **Builds the Data Agent item definition** from ``fabric/data-agent/`` (R3 §4.2 format:
   ``Files/Config/data_agent.json``, ``draft/stage_config.json``, per-source
   ``datasource.json`` + ``fewshots.json``, ``publish_info.json``), substituting the
   deploy-time tokens (workspace id, semantic-model / graph artifact ids + display
   names) and mirroring the ``draft/`` parts into a ``published/`` stage (R3 §9: there is
   no separate publish endpoint - deploy a definition containing published parts). Each
   ``datasource.json`` carries the required ``elements`` (``DataSourceElement``) tree with
   ``id`` / ``display_name`` / ``type`` / ``is_selected`` (R3 §4.2); the committed files
   hold schema-valid **placeholder** element ids so offline assembly / ``--dry-run`` stay
   valid.
5. **Find-or-create the Data Agent item** (idempotent) and deploy the definition as code
   via ``POST /v1/workspaces/{id}/dataAgents`` (create) or
   ``POST .../dataAgents/{id}/updateDefinition`` (update). Add retry/backoff + LRO polling.
6. **Reconciles the real ``DataSourceElement`` ids** at deploy time (R3 line 358). The real
   element ids are auto-generated by Fabric when a source is bound, so after the first
   deploy the script calls ``POST .../dataAgents/{id}/getDefinition`` to read them back,
   re-applies the committed ``is_selected`` selection (by ``display_name``), injects the
   real ids into the datasource parts, and calls ``updateDefinition`` again so the
   published definition carries real element ids instead of placeholders. If the tenant
   returns no auto-generated element metadata, the schema-valid placeholders are retained.

Grounding (R3 §2.2 / R4 §5.3)
-----------------------------
* **Semantic model** (``type="semantic_model"``, NL2DAX) — the Step-14 Direct Lake model.
  Example query pairs are **not supported** for semantic models (R3 §5.2); accuracy comes
  from the model's *Prep for AI* configuration, not agent instructions.
* **Graph** (``type="graph"``, NL2GQL) — the Step-16 ontology's **auto-created** managed
  Graph in Fabric (GA). **R4 caveat (documented in code + README):** the Data Agent
  definition REST enum exposes ``graph`` and ``semantic_model`` but **not** ``ontology``,
  so attaching the ontology *directly* (NL2Ontology) may be a **UI-only** step in some
  tenants. The **graph source is the documented programmatic path** to ontology-backed
  reasoning and is what this script wires up.

REST endpoints used (Fabric Data Agent + item-management APIs — R3 §4.1):
    GET    /v1/workspaces/{workspaceId}/items?type=SemanticModel              (resolve semantic-model id)
    GET    /v1/workspaces/{workspaceId}/items?type=Graph                      (resolve graph id)
    POST   /v1/workspaces/{workspaceId}/dataAgents                           (create w/ definition)
    GET    /v1/workspaces/{workspaceId}/dataAgents                           (list / find-by-name)
    POST   /v1/workspaces/{workspaceId}/dataAgents/{id}/updateDefinition     (idempotent update)
    POST   /v1/workspaces/{workspaceId}/dataAgents/{id}/getDefinition        (read back real DataSourceElement ids)

Secondary ALM path (R3 §5.5)
----------------------------
REST is the source-of-truth create here. For repeatable promotion across environments,
the same committed item definition can be deployed with ``fabric-cicd`` / Git integration
+ deployment pipelines (dev -> test -> prod). That ALM wiring is intentionally out of
scope for this create script.

Security / Phase-0 notes
------------------------
* **No secrets.** Identity comes from config (names / ids / placeholders only); auth is
  acquired at runtime via ``DefaultAzureCredential`` / ``az login``. The committed
  definition contains only names, instructions, and placeholder tokens.
* **Authoring phase:** do **not** run this against a live tenant unless you intend to
  create Fabric items. Use ``--dry-run`` to preview every intended REST call with
  **no** authentication and **no** changes.

Usage
-----
    # Preview only - no auth, no mutation (safe):
    python fabric/scripts/70_create_data_agent.py --dry-run

    # Create/refresh the Data Agent from deploy_config.json:
    python fabric/scripts/70_create_data_agent.py

    # Fully explicit:
    python fabric/scripts/70_create_data_agent.py \
        --workspace-name zava-fabric-ws \
        --semantic-model-name "Zava Fleet Analytics" \
        --graph-name ZavaFleetOntology \
        --agent-name "Zava Fleet Insights Agent" \
        --config fabric/config/deploy_config.json
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Fabric REST control plane (R3 §4.1). Auth scope per the Fabric APIs article.
FABRIC_API_BASE = "https://api.fabric.microsoft.com/v1"
FABRIC_RESOURCE = "https://api.fabric.microsoft.com"
FABRIC_SCOPE = "https://api.fabric.microsoft.com/.default"

# Retry / long-running-operation tuning (Fabric throttling: HTTP 429 + Retry-After;
# 202-Accepted LROs expose Operation-Location + Retry-After).
MAX_RETRIES = 5
DEFAULT_BACKOFF_SECONDS = 5
LRO_POLL_DEFAULT_SECONDS = 5
LRO_TIMEOUT_SECONDS = 600

# Fabric item types (generic items API ?type= filter).
SEMANTIC_MODEL_ITEM_TYPE = "SemanticModel"
GRAPH_ITEM_TYPE = "Graph"

# Default display names (kept in sync with Steps 14 / 16 / 17 defaults).
DEFAULT_SEMANTIC_MODEL_NAME = "Zava Fleet Analytics"
DEFAULT_ONTOLOGY_NAME = "ZavaFleetOntology"
DEFAULT_DATA_AGENT_NAME = "Zava Fleet Insights Agent"

# Repo-relative defaults.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_CONFIG_CANDIDATES = (
    os.path.join(_REPO_ROOT, "fabric", "config", "deploy_config.json"),
    os.path.join(_REPO_ROOT, "fabric", "config", "deploy_config.sample.json"),
)
# Root of the committed item definition (R3 §4.2 layout lives under Files/Config/).
DATA_AGENT_DIR = os.path.join(_REPO_ROOT, "fabric", "data-agent")
DEFINITION_ROOT = os.path.join(DATA_AGENT_DIR, "Files", "Config")

# Deploy-time placeholder tokens substituted into the definition parts.
TOKEN_WORKSPACE_ID = "__ZAVA_WORKSPACE_ID__"
TOKEN_SEMANTIC_MODEL_ARTIFACT_ID = "__ZAVA_SEMANTIC_MODEL_ARTIFACT_ID__"
TOKEN_SEMANTIC_MODEL_DISPLAY_NAME = "__ZAVA_SEMANTIC_MODEL_DISPLAY_NAME__"
TOKEN_GRAPH_ARTIFACT_ID = "__ZAVA_GRAPH_ARTIFACT_ID__"
TOKEN_GRAPH_DISPLAY_NAME = "__ZAVA_GRAPH_DISPLAY_NAME__"
ZERO_GUID = "00000000-0000-0000-0000-000000000000"

# Per-source folder names under draft/ (and published/). The trailing datasource.json
# part of each carries the required ``elements`` (DataSourceElement) tree (R3 §4.2).
SEMANTIC_MODEL_SOURCE_KEY = "semantic_model-ZavaFleetAnalytics"
GRAPH_SOURCE_KEY = "graph-ZavaFleetOntologyGraph"

# A value like "<WORKSPACE_GUID>" in the sample config is an unresolved placeholder.
_PLACEHOLDER_RE = re.compile(r"^<[A-Z0-9_]+>$")
_GUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)

LOG = logging.getLogger("zava.fabric.data_agent")


class DataAgentError(RuntimeError):
    """Raised on unrecoverable problems (bad identity, auth failure, API error)."""


# ---------------------------------------------------------------------------
# Config / identity resolution
# ---------------------------------------------------------------------------

def _is_placeholder(value: object) -> bool:
    return isinstance(value, str) and bool(_PLACEHOLDER_RE.match(value.strip()))


def _clean(value: object) -> Optional[str]:
    """Return a usable string value, or None for missing / blank / placeholder values."""
    if not isinstance(value, str):
        return None
    value = value.strip()
    if not value or _is_placeholder(value):
        return None
    return value


def _resolve_config_path(explicit: Optional[str]) -> Optional[str]:
    if explicit:
        if not os.path.isfile(explicit):
            raise DataAgentError(f"--config path does not exist: {explicit}")
        return explicit
    for candidate in DEFAULT_CONFIG_CANDIDATES:
        if os.path.isfile(candidate):
            return candidate
    return None


def _load_config(path: Optional[str]) -> dict:
    if not path:
        return {}
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        raise DataAgentError(f"failed to read config {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise DataAgentError(f"config {path} must be a JSON object")
    return data


class DataAgentPlan:
    """Resolved, validated plan for the Data Agent operation (no secrets)."""

    def __init__(
        self,
        *,
        config_path: Optional[str],
        workspace_name: Optional[str],
        use_existing_workspace: bool,
        existing_workspace_id: Optional[str],
        semantic_model_name: str,
        graph_name: Optional[str],
        agent_name: str,
        enable_data_agent: bool,
        enable_ontology: bool,
    ) -> None:
        self.config_path = config_path
        self.workspace_name = workspace_name
        self.use_existing_workspace = use_existing_workspace
        self.existing_workspace_id = existing_workspace_id
        self.semantic_model_name = semantic_model_name
        self.graph_name = graph_name
        self.agent_name = agent_name
        self.enable_data_agent = enable_data_agent
        self.enable_ontology = enable_ontology


def resolve_plan(
    *,
    config_path: Optional[str] = None,
    workspace_name: Optional[str] = None,
    existing_workspace_id: Optional[str] = None,
    semantic_model_name: Optional[str] = None,
    graph_name: Optional[str] = None,
    agent_name: Optional[str] = None,
) -> DataAgentPlan:
    """Resolve the Data Agent operation plan from config + CLI/env overrides.

    Precedence per field: explicit CLI arg > config value > environment variable.
    Raises ``DataAgentError`` naming any field that could not be resolved.
    """
    resolved_path = _resolve_config_path(config_path)
    cfg = _load_config(resolved_path)
    ws_cfg = cfg.get("workspace", {}) if isinstance(cfg.get("workspace"), dict) else {}
    sm_cfg = cfg.get("semantic_model", {}) if isinstance(cfg.get("semantic_model"), dict) else {}
    ont_cfg = cfg.get("ontology", {}) if isinstance(cfg.get("ontology"), dict) else {}
    da_cfg = cfg.get("data_agent", {}) if isinstance(cfg.get("data_agent"), dict) else {}
    feat_cfg = cfg.get("features", {}) if isinstance(cfg.get("features"), dict) else {}

    # Feature gates. enable_data_agent defaults true (the "beyond Power BI" pillar).
    # enable_ontology toggles whether the graph source (ontology's auto Graph) is wired in.
    flag = feat_cfg.get("enable_data_agent")
    enable_data_agent = bool(flag) if isinstance(flag, bool) else True
    ont_flag = feat_cfg.get("enable_ontology")
    enable_ontology = bool(ont_flag) if isinstance(ont_flag, bool) else False

    use_existing = bool(ws_cfg.get("use_existing"))
    name = workspace_name or _clean(ws_cfg.get("name")) or os.environ.get("FABRIC_WORKSPACE_NAME")
    existing_id = (
        existing_workspace_id
        or _clean(ws_cfg.get("existing_workspace_id"))
        or os.environ.get("FABRIC_WORKSPACE_ID")
    )

    sm_name = (
        semantic_model_name
        or _clean(da_cfg.get("semantic_model_name"))
        or _clean(sm_cfg.get("name"))
        or os.environ.get("FABRIC_SEMANTIC_MODEL_NAME")
        or DEFAULT_SEMANTIC_MODEL_NAME
    )
    # Graph display name: explicit override, else config, else the ontology name
    # (the auto-created Graph commonly shares the ontology's name); None => resolve the
    # single Graph item in the workspace.
    graph = (
        graph_name
        or _clean(da_cfg.get("graph_name"))
        or _clean(ont_cfg.get("graph_name"))
        or _clean(ont_cfg.get("name"))
        or os.environ.get("FABRIC_GRAPH_NAME")
    )
    agent = (
        agent_name
        or _clean(da_cfg.get("name"))
        or os.environ.get("FABRIC_DATA_AGENT_NAME")
        or DEFAULT_DATA_AGENT_NAME
    )

    # Validation.
    if use_existing:
        if not existing_id:
            raise DataAgentError(
                "workspace.use_existing=true but no workspace id resolved "
                "(set workspace.existing_workspace_id, --workspace-id, or FABRIC_WORKSPACE_ID)"
            )
        if not _GUID_RE.match(existing_id):
            raise DataAgentError(f"resolved existing workspace id is not a GUID: {existing_id!r}")
    elif not name:
        raise DataAgentError(
            "could not resolve workspace name "
            "(set workspace.name, --workspace-name, or FABRIC_WORKSPACE_NAME)"
        )

    if not sm_name:
        raise DataAgentError(
            "could not resolve the semantic model name "
            "(set semantic_model.name, --semantic-model-name, or FABRIC_SEMANTIC_MODEL_NAME)"
        )
    if not agent:
        raise DataAgentError(
            "could not resolve the Data Agent display name "
            "(set data_agent.name, --agent-name, or FABRIC_DATA_AGENT_NAME)"
        )

    return DataAgentPlan(
        config_path=resolved_path,
        workspace_name=name,
        use_existing_workspace=use_existing,
        existing_workspace_id=existing_id,
        semantic_model_name=sm_name,
        graph_name=graph,
        agent_name=agent,
        enable_data_agent=enable_data_agent,
        enable_ontology=enable_ontology,
    )


# ---------------------------------------------------------------------------
# Authentication (DefaultAzureCredential, with az CLI fallback)
# ---------------------------------------------------------------------------

def get_access_token(resource: str = FABRIC_RESOURCE) -> str:
    """Acquire a bearer token for ``resource`` via DefaultAzureCredential; fall back to ``az``.

    No secret is ever read from or written to disk: this relies on an existing
    ``az login``, a managed identity, or environment service-principal credentials.
    """
    scope = resource.rstrip("/") + "/.default"
    try:
        from azure.identity import DefaultAzureCredential  # type: ignore import-not-found
    except ImportError:
        LOG.debug("azure-identity not installed; falling back to `az account get-access-token`")
        return _get_token_via_az_cli(resource)

    try:
        credential = DefaultAzureCredential(exclude_interactive_browser_credential=False)
        return credential.get_token(scope).token
    except Exception as exc:  # noqa: BLE001 - surface any auth failure uniformly
        LOG.debug("DefaultAzureCredential failed (%s); falling back to az CLI", exc)
        return _get_token_via_az_cli(resource)


def _get_token_via_az_cli(resource: str) -> str:
    try:
        proc = subprocess.run(
            ["az", "account", "get-access-token", "--resource", resource, "-o", "json"],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise DataAgentError(
            "could not authenticate: neither the azure-identity package nor the Azure CLI (`az`) "
            "is available. Install azure-identity or run `az login`."
        ) from exc
    except subprocess.CalledProcessError as exc:
        raise DataAgentError(
            f"`az account get-access-token` failed (run `az login` first): {exc.stderr.strip()}"
        ) from exc
    try:
        token = json.loads(proc.stdout)["accessToken"]
    except (json.JSONDecodeError, KeyError) as exc:
        raise DataAgentError("could not parse access token from az CLI output") from exc
    return token


# ---------------------------------------------------------------------------
# REST helpers (stdlib only) with retry/backoff + LRO polling
# ---------------------------------------------------------------------------

def _request(
    method: str,
    url: str,
    token: str,
    body: Optional[dict] = None,
    *,
    content_type: str = "application/json",
    accept: str = "application/json",
) -> Tuple[int, Dict[str, str], dict]:
    """Issue a single REST call, retrying on throttling (429) and transient 5xx.

    Returns (status_code, response_headers, json_payload). Raises ``DataAgentError``
    on a non-retryable HTTP error or once retries are exhausted.
    """
    data = json.dumps(body).encode("utf-8") if body is not None else None
    attempt = 0
    while True:
        attempt += 1
        request = urllib.request.Request(url=url, method=method, data=data)
        request.add_header("Authorization", f"Bearer {token}")
        request.add_header("Content-Type", content_type)
        request.add_header("Accept", accept)
        try:
            with urllib.request.urlopen(request) as response:  # noqa: S310 - fixed hosts
                status = response.status
                headers = {k.lower(): v for k, v in response.headers.items()}
                raw = response.read().decode("utf-8") or ""
                payload = json.loads(raw) if raw.strip() else {}
                return status, headers, payload
        except urllib.error.HTTPError as exc:
            body_text = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
            retry_after = exc.headers.get("Retry-After") if exc.headers else None
            if exc.code == 429 or 500 <= exc.code < 600:
                if attempt <= MAX_RETRIES:
                    delay = _retry_delay(retry_after, attempt)
                    LOG.warning(
                        "%s %s -> HTTP %s; retrying in %ss (attempt %s/%s)",
                        method, url, exc.code, delay, attempt, MAX_RETRIES,
                    )
                    time.sleep(delay)
                    continue
            raise DataAgentError(
                f"{method} {url} failed: HTTP {exc.code} {exc.reason} {body_text}".strip()
            ) from exc
        except urllib.error.URLError as exc:
            if attempt <= MAX_RETRIES:
                delay = _retry_delay(None, attempt)
                LOG.warning(
                    "%s %s network error (%s); retrying in %ss (attempt %s/%s)",
                    method, url, exc.reason, delay, attempt, MAX_RETRIES,
                )
                time.sleep(delay)
                continue
            raise DataAgentError(f"{method} {url} failed: {exc.reason}") from exc


def _retry_delay(retry_after: Optional[str], attempt: int) -> int:
    if retry_after:
        try:
            return max(1, int(float(retry_after)))
        except (TypeError, ValueError):
            pass
    return DEFAULT_BACKOFF_SECONDS * (2 ** (attempt - 1))


def _poll_long_running(
    headers: Dict[str, str], token: str, *, timeout: int = LRO_TIMEOUT_SECONDS
) -> dict:
    """Poll a Fabric long-running operation (202 + Operation-Location) until terminal state."""
    op_url = headers.get("operation-location") or headers.get("location")
    if not op_url:
        return {}
    poll_interval = LRO_POLL_DEFAULT_SECONDS
    retry_after = headers.get("retry-after")
    if retry_after:
        try:
            poll_interval = max(1, int(float(retry_after)))
        except (TypeError, ValueError):
            pass

    deadline = time.monotonic() + timeout
    while True:
        _, op_headers, payload = _request("GET", op_url, token)
        state = str(payload.get("status", "")).lower()
        LOG.debug("LRO %s -> status=%s", op_url, state or "<none>")
        if state in ("succeeded", "completed"):
            result_url = op_headers.get("location")
            if result_url and result_url != op_url:
                _, _, result = _request("GET", result_url, token)
                return result
            return payload
        if state in ("failed", "canceled", "cancelled"):
            raise DataAgentError(
                f"Fabric long-running operation {op_url} ended in state {state!r}: {payload}"
            )
        if time.monotonic() >= deadline:
            raise DataAgentError(
                f"timed out after {timeout}s waiting for Fabric operation {op_url} "
                f"(last state {state!r})"
            )
        ra = op_headers.get("retry-after")
        if ra:
            try:
                poll_interval = max(1, int(float(ra)))
            except (TypeError, ValueError):
                pass
        time.sleep(poll_interval)


def _list_paginated(path: str, token: str) -> List[dict]:
    """Return all ``value`` entries across a paginated Fabric list endpoint."""
    items: List[dict] = []
    url = f"{FABRIC_API_BASE}{path}"
    seen_tokens = set()
    while url:
        _, _, payload = _request("GET", url, token)
        items.extend(payload.get("value", []) or [])
        cont_uri = payload.get("continuationUri")
        cont_token = payload.get("continuationToken")
        if cont_uri:
            url = cont_uri
        elif cont_token and cont_token not in seen_tokens:
            seen_tokens.add(cont_token)
            base = f"{FABRIC_API_BASE}{path}"
            sep = "&" if "?" in base else "?"
            url = f"{base}{sep}continuationToken={urllib.parse.quote(cont_token)}"
        else:
            url = ""
    return items


def _create_item_lro(path: str, token: str, body: dict) -> dict:
    """POST a create call; if it returns 202 (async), poll to completion and return the result."""
    status, headers, payload = _request("POST", f"{FABRIC_API_BASE}{path}", token, body=body)
    if status == 202:
        result = _poll_long_running(headers, token)
        return result or payload
    return payload


# ---------------------------------------------------------------------------
# Workspace / data-source resolution
# ---------------------------------------------------------------------------

def resolve_workspace_id(token: str, plan: DataAgentPlan) -> str:
    """Resolve the target workspace id (existing path by id, fresh path by display name)."""
    if plan.use_existing_workspace:
        _, _, ws = _request(
            "GET", f"{FABRIC_API_BASE}/workspaces/{plan.existing_workspace_id}", token
        )
        ws_id = str(ws.get("id") or plan.existing_workspace_id)
        LOG.info("Using existing workspace %s (%s).", ws.get("displayName"), ws_id)
        return ws_id
    target = plan.workspace_name.strip().lower()  # type: ignore[union-attr]
    for ws in _list_paginated("/workspaces", token):
        if str(ws.get("displayName", "")).strip().lower() == target:
            LOG.info("Resolved workspace %r -> %s.", plan.workspace_name, ws.get("id"))
            return str(ws["id"])
    raise DataAgentError(
        f"workspace {plan.workspace_name!r} not found - run Step 10 "
        f"(fabric/scripts/00_create_workspace.py) first."
    )


def _find_item_by_name(items: List[dict], name: str) -> Optional[dict]:
    target = name.strip().lower()
    for item in items:
        display = str(item.get("displayName") or item.get("name") or "").strip().lower()
        if display == target:
            return item
    return None


def resolve_semantic_model(token: str, workspace_id: str, name: str) -> Tuple[str, str]:
    """Resolve the Step-14 semantic model item (id, displayName) by display name."""
    items = _list_paginated(
        f"/workspaces/{workspace_id}/items?type={SEMANTIC_MODEL_ITEM_TYPE}", token
    )
    existing = _find_item_by_name(items, name)
    if not existing:
        raise DataAgentError(
            f"semantic model {name!r} not found in workspace {workspace_id} - run Step 14 "
            f"(fabric/scripts/30_create_semantic_model.py) first so the Data Agent can ground "
            f"on the Direct Lake model."
        )
    item_id = str(existing["id"])
    display = str(existing.get("displayName") or existing.get("name") or name)
    LOG.info("Resolved semantic model %r -> %s.", display, item_id)
    return item_id, display


def resolve_graph(
    token: str, workspace_id: str, name: Optional[str]
) -> Optional[Tuple[str, str]]:
    """Resolve the Step-16 ontology's auto-created Graph item (id, displayName).

    Returns None (no error) when no Graph is found, so the agent can still be created
    with the semantic-model source only. When *name* is given, match it; otherwise fall
    back to the single Graph item in the workspace.
    """
    items = _list_paginated(f"/workspaces/{workspace_id}/items?type={GRAPH_ITEM_TYPE}", token)
    if not items:
        LOG.warning(
            "No Graph item found in workspace %s - run Step 16 "
            "(fabric/scripts/60_create_ontology.py) to auto-create the ontology's managed "
            "Graph, or set features.enable_ontology=false. Proceeding with the semantic-model "
            "source only.",
            workspace_id,
        )
        return None
    if name:
        existing = _find_item_by_name(items, name)
        if existing:
            item_id = str(existing["id"])
            display = str(existing.get("displayName") or existing.get("name") or name)
            LOG.info("Resolved Graph %r -> %s.", display, item_id)
            return item_id, display
        LOG.warning(
            "Graph named %r not found in workspace %s (found: %s). Falling back to the single "
            "Graph item if unambiguous.",
            name, workspace_id,
            [str(i.get("displayName") or i.get("name")) for i in items],
        )
    if len(items) == 1:
        only = items[0]
        item_id = str(only["id"])
        display = str(only.get("displayName") or only.get("name") or "")
        LOG.info("Resolved the single Graph item %r -> %s.", display, item_id)
        return item_id, display
    raise DataAgentError(
        f"multiple Graph items found in workspace {workspace_id} "
        f"({[str(i.get('displayName') or i.get('name')) for i in items]}) - set "
        f"data_agent.graph_name (or --graph-name) to disambiguate which Graph the Data Agent "
        f"should ground on."
    )


# ---------------------------------------------------------------------------
# Definition assembly (R3 §4.2 item-definition format)
# ---------------------------------------------------------------------------

def _b64(text: str) -> str:
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


def _read_definition_file(rel_path: str) -> str:
    """Read a committed definition file (path relative to Files/Config/) as raw text."""
    abs_path = os.path.join(DEFINITION_ROOT, *rel_path.split("/"))
    if not os.path.isfile(abs_path):
        raise DataAgentError(f"definition file not found: {abs_path}")
    with open(abs_path, "r", encoding="utf-8") as fh:
        return fh.read()


def _substitute_tokens(
    text: str,
    *,
    workspace_id: str,
    semantic_model_id: str,
    semantic_model_name: str,
    graph_id: Optional[str],
    graph_name: Optional[str],
) -> str:
    """Replace deploy-time tokens in a definition file's text."""
    text = text.replace(TOKEN_WORKSPACE_ID, workspace_id)
    text = text.replace(TOKEN_SEMANTIC_MODEL_ARTIFACT_ID, semantic_model_id)
    text = text.replace(TOKEN_SEMANTIC_MODEL_DISPLAY_NAME, semantic_model_name)
    if graph_id is not None and graph_name is not None:
        text = text.replace(TOKEN_GRAPH_ARTIFACT_ID, graph_id)
        text = text.replace(TOKEN_GRAPH_DISPLAY_NAME, graph_name)
    return text


def _validate_json(part_path: str, text: str) -> None:
    """Fail fast if a substituted definition part is not valid JSON."""
    try:
        json.loads(text)
    except json.JSONDecodeError as exc:
        raise DataAgentError(f"definition part {part_path!r} is not valid JSON after "
                             f"token substitution: {exc}") from exc


def _datasource_source_key(rel_path: str) -> Optional[str]:
    """Return the per-source folder name (e.g. ``semantic_model-ZavaFleetAnalytics``) for a
    ``datasource.json`` part, or ``None`` for any other definition part. The folder name is
    the key used to look up retrieved ``DataSourceElement`` metadata for injection.
    """
    norm = rel_path.replace("\\", "/")
    if not norm.endswith("/datasource.json"):
        return None
    # .../<source-folder>/datasource.json -> <source-folder>
    return norm.rsplit("/", 2)[-2]


def _inject_elements(
    text: str,
    rel_path: str,
    elements_by_source: Optional[Dict[str, List[dict]]],
) -> str:
    """Inject deploy-time-retrieved ``DataSourceElement`` metadata into a datasource part.

    When *elements_by_source* contains real elements for this datasource's source key
    (retrieved from the live agent via ``getDefinition`` — R3 line 358), the static
    placeholder ``elements`` array is replaced with the real one. When no override is
    supplied for this source the committed (schema-valid placeholder) ``elements`` tree is
    kept unchanged, so offline assembly / dry-run still produces a valid definition.
    """
    if not elements_by_source:
        return text
    source_key = _datasource_source_key(rel_path)
    if source_key is None or source_key not in elements_by_source:
        return text
    elements = elements_by_source[source_key]
    if not elements:
        return text
    obj = json.loads(text)
    obj["elements"] = elements
    LOG.info(
        "Injected %d retrieved DataSourceElement(s) into %s (real ids from getDefinition).",
        len(elements), source_key,
    )
    return json.dumps(obj, indent=2)


def build_definition_parts(
    *,
    workspace_id: str,
    semantic_model_id: str,
    semantic_model_name: str,
    graph_id: Optional[str],
    graph_name: Optional[str],
    include_graph: bool,
    elements_by_source: Optional[Dict[str, List[dict]]] = None,
) -> List[dict]:
    """Assemble the Base64 ``definition.parts`` (R3 §4.2).

    Reads the committed ``draft/`` parts (+ top-level ``data_agent.json`` /
    ``publish_info.json``), substitutes deploy-time tokens, injects retrieved
    ``DataSourceElement`` metadata into each ``datasource.json`` when available
    (*elements_by_source*; see :func:`_inject_elements`), and mirrors the draft stage
    into a ``published/`` stage (R3 §9: no separate publish endpoint - deploy a definition
    that contains the published parts). The ``graph-*`` parts are dropped when
    ``include_graph`` is False (ontology disabled / no Graph item).
    """
    # Relative paths (under Files/Config/) of the committed draft definition files.
    draft_rel_paths = [
        "draft/stage_config.json",
        f"draft/{SEMANTIC_MODEL_SOURCE_KEY}/datasource.json",
        f"draft/{GRAPH_SOURCE_KEY}/datasource.json",
        f"draft/{GRAPH_SOURCE_KEY}/fewshots.json",
    ]
    top_level_rel_paths = ["data_agent.json", "publish_info.json"]

    def keep(rel_path: str) -> bool:
        return include_graph or "/graph-" not in f"/{rel_path}"

    parts: List[dict] = []

    def render(rel_path: str) -> str:
        raw = _read_definition_file(rel_path)
        substituted = _substitute_tokens(
            raw,
            workspace_id=workspace_id,
            semantic_model_id=semantic_model_id,
            semantic_model_name=semantic_model_name,
            graph_id=graph_id,
            graph_name=graph_name,
        )
        return _inject_elements(substituted, rel_path, elements_by_source)

    def add_part(rel_path: str) -> None:
        rendered = render(rel_path)
        full_path = f"Files/Config/{rel_path}"
        _validate_json(full_path, rendered)
        parts.append({
            "path": full_path,
            "payload": _b64(rendered),
            "payloadType": "InlineBase64",
        })

    for rel_path in top_level_rel_paths:
        add_part(rel_path)

    for rel_path in draft_rel_paths:
        if not keep(rel_path):
            LOG.info("Dropping definition part %r (graph source disabled).", rel_path)
            continue
        add_part(rel_path)
        # Mirror the draft part into the published stage (R3 §9).
        published_rel = rel_path.replace("draft/", "published/", 1)
        rendered = render(rel_path)
        full_path = f"Files/Config/{published_rel}"
        _validate_json(full_path, rendered)
        parts.append({
            "path": full_path,
            "payload": _b64(rendered),
            "payloadType": "InlineBase64",
        })

    return parts


def build_definition(parts: List[dict]) -> dict:
    """Wrap the parts in the Fabric item-definition envelope."""
    return {"parts": parts}


# ---------------------------------------------------------------------------
# DataSourceElement retrieval / injection (R3 line 358 + §4.2)
# ---------------------------------------------------------------------------
#
# DataSourceElement.id (UUID), display_name, type and is_selected are all REQUIRED by the
# definition schema, but the real element ids are auto-generated by Fabric when a data
# source is bound. R3 line 358 documents the retrieval mechanism: read them back from the
# live agent's definition via the ``getDefinition`` endpoint. The committed datasource.json
# files therefore carry schema-valid placeholder ids that keep offline assembly / dry-run
# valid, and at deploy time we fetch the real elements and re-inject them (see
# :func:`reconcile_datasource_elements`).


def get_data_agent_definition(token: str, workspace_id: str, agent_id: str) -> dict:
    """Retrieve a Data Agent's live item definition via the ``getDefinition`` endpoint.

    Returns the ``definition`` object (``{"parts": [...]}``) with Base64 ``payload``s.
    The call is a long-running operation (202 + Operation-Location); the result is
    returned by polling to completion (R3 §4.1 / line 358).
    """
    status, headers, payload = _request(
        "POST",
        f"{FABRIC_API_BASE}/workspaces/{workspace_id}/dataAgents/{agent_id}/getDefinition",
        token,
    )
    if status == 202:
        payload = _poll_long_running(headers, token) or payload
    definition = payload.get("definition", payload)
    if not isinstance(definition, dict):
        return {}
    return definition


def _decode_part_payload(part: dict) -> Optional[dict]:
    """Decode an InlineBase64 definition part payload into a dict (best-effort)."""
    payload = part.get("payload")
    if not payload or str(part.get("payloadType", "InlineBase64")) != "InlineBase64":
        return None
    try:
        raw = base64.b64decode(payload).decode("utf-8")
        return json.loads(raw)
    except (ValueError, json.JSONDecodeError):
        return None


def _collect_selected_display_names(elements: List[dict]) -> set:
    """Recursively collect the display_names that were marked ``is_selected`` in the
    committed (desired) ``elements`` tree, so the selection can be re-applied to the real
    elements retrieved from Fabric.
    """
    selected: set = set()
    for el in elements or []:
        if el.get("is_selected"):
            name = el.get("display_name")
            if name:
                selected.add(str(name))
        children = el.get("children")
        if isinstance(children, list):
            selected |= _collect_selected_display_names(children)
    return selected


def _apply_selection(elements: List[dict], desired_names: set) -> Tuple[List[dict], bool]:
    """Return a copy of *elements* (real ids preserved) with ``is_selected`` set from
    *desired_names*. A node is selected when its own display_name is desired OR any of its
    descendants is selected. When *desired_names* is empty every element is selected.
    """
    result: List[dict] = []
    any_selected = False
    for el in elements or []:
        node = dict(el)
        child_selected = False
        children = el.get("children")
        if isinstance(children, list):
            new_children, child_selected = _apply_selection(children, desired_names)
            node["children"] = new_children
        own = (not desired_names) or (str(el.get("display_name")) in desired_names)
        node["is_selected"] = bool(own or child_selected)
        any_selected = any_selected or node["is_selected"]
        result.append(node)
    return result, any_selected


def retrieve_datasource_elements(
    token: str, workspace_id: str, agent_id: str
) -> Dict[str, List[dict]]:
    """Retrieve the real ``DataSourceElement`` metadata Fabric auto-generated for each bound
    data source, keyed by per-source folder name (R3 line 358).

    Calls ``getDefinition`` on the live agent, decodes each ``draft/.../datasource.json``
    part, and returns ``{source_key: elements}`` with the real ids. The committed desired
    ``is_selected`` selection is re-applied (by display_name) onto the retrieved tree.
    Returns an empty mapping when nothing usable could be retrieved (e.g. tenant did not
    expose auto-generated elements), in which case the schema-valid placeholders are kept.
    """
    try:
        definition = get_data_agent_definition(token, workspace_id, agent_id)
    except DataAgentError as exc:
        LOG.warning(
            "Could not getDefinition for Data Agent %s (%s) - keeping placeholder "
            "DataSourceElement ids in the committed datasource.json.", agent_id, exc,
        )
        return {}

    retrieved: Dict[str, List[dict]] = {}
    for part in definition.get("parts", []) or []:
        path = str(part.get("path", ""))
        if not path.replace("\\", "/").endswith("/datasource.json"):
            continue
        # Only reconcile the draft stage; published is mirrored from it.
        if "/draft/" not in path.replace("\\", "/"):
            continue
        rel = path.split("Files/Config/", 1)[-1]
        source_key = _datasource_source_key(rel)
        if not source_key:
            continue
        decoded = _decode_part_payload(part)
        if not isinstance(decoded, dict):
            continue
        live_elements = decoded.get("elements")
        if not isinstance(live_elements, list) or not live_elements:
            continue
        desired = _collect_selected_display_names(_committed_elements(source_key))
        merged, _ = _apply_selection(live_elements, desired)
        retrieved[source_key] = merged
        LOG.info(
            "Retrieved %d real DataSourceElement(s) for %s via getDefinition.",
            len(live_elements), source_key,
        )
    if not retrieved:
        LOG.info(
            "getDefinition returned no auto-generated DataSourceElement metadata - keeping "
            "the committed schema-valid placeholder ids."
        )
    return retrieved


def _committed_elements(source_key: str) -> List[dict]:
    """Read the committed (desired) ``elements`` tree for a source key from the draft files."""
    rel = f"draft/{source_key}/datasource.json"
    try:
        obj = json.loads(_read_definition_file(rel))
    except (DataAgentError, json.JSONDecodeError):
        return []
    elements = obj.get("elements")
    return elements if isinstance(elements, list) else []


# ---------------------------------------------------------------------------
# Data Agent find-or-create (idempotent)
# ---------------------------------------------------------------------------

def find_or_create_data_agent(
    token: str, workspace_id: str, plan: DataAgentPlan, definition: dict
) -> dict:
    """Find-or-create the Data Agent; update its definition in place if it exists."""
    existing = _find_item_by_name(
        _list_paginated(f"/workspaces/{workspace_id}/dataAgents", token), plan.agent_name
    )
    if existing:
        agent_id = str(existing.get("id"))
        LOG.info(
            "Data Agent %r already exists (%s) - updating definition (idempotent).",
            plan.agent_name, agent_id,
        )
        update_data_agent_definition(token, workspace_id, agent_id, definition)
        return existing
    LOG.info("Creating Data Agent %r ...", plan.agent_name)
    created = _create_item_lro(
        f"/workspaces/{workspace_id}/dataAgents",
        token,
        {
            "displayName": plan.agent_name,
            "description": "Zava Fleet Insights Agent - NL Q&A over the Direct Lake semantic "
                           "model (NL2DAX) and the ontology's auto-created Graph (NL2GQL).",
            "definition": definition,
        },
    )
    LOG.info("Created Data Agent %r (%s).", plan.agent_name, created.get("id"))
    return created


def update_data_agent_definition(
    token: str, workspace_id: str, agent_id: str, definition: dict
) -> None:
    """Deploy an item definition onto an existing Data Agent (idempotent updateDefinition)."""
    status, headers, _ = _request(
        "POST",
        f"{FABRIC_API_BASE}/workspaces/{workspace_id}/dataAgents/{agent_id}/updateDefinition",
        token,
        body={"definition": definition},
    )
    if status == 202:
        _poll_long_running(headers, token)


def reconcile_datasource_elements(
    token: str,
    workspace_id: str,
    agent_id: str,
    *,
    semantic_model_id: str,
    semantic_model_name: str,
    graph_id: Optional[str],
    graph_name: Optional[str],
    include_graph: bool,
) -> bool:
    """Retrieve the real ``DataSourceElement`` ids from the live agent and re-deploy.

    R3 line 358: element ids are auto-generated by Fabric when the source is bound, so we
    read them back via ``getDefinition`` and inject them into the datasource parts before a
    final ``updateDefinition``. Returns True when a reconciled definition was redeployed,
    False when no real elements were retrieved (placeholders retained — definition already
    deployed in the first pass is left in place).
    """
    elements_by_source = retrieve_datasource_elements(token, workspace_id, agent_id)
    if not elements_by_source:
        return False
    parts = build_definition_parts(
        workspace_id=workspace_id,
        semantic_model_id=semantic_model_id,
        semantic_model_name=semantic_model_name,
        graph_id=graph_id,
        graph_name=graph_name,
        include_graph=include_graph,
        elements_by_source=elements_by_source,
    )
    LOG.info(
        "Re-deploying definition with real DataSourceElement ids for source(s): %s.",
        ", ".join(sorted(elements_by_source)),
    )
    update_data_agent_definition(token, workspace_id, agent_id, build_definition(parts))
    return True


# ---------------------------------------------------------------------------
# Core orchestration
# ---------------------------------------------------------------------------

def run(plan: DataAgentPlan, *, dry_run: bool = False) -> int:
    """Execute the Data Agent create/update flow. Returns an exit code."""
    if not plan.enable_data_agent:
        LOG.info(
            "features.enable_data_agent=false - skipping the Fabric Data Agent. "
            "Set enable_data_agent=true to enable Step 17."
        )
        return 0

    if dry_run:
        return _print_dry_run(plan)

    if not os.path.isdir(DEFINITION_ROOT):
        raise DataAgentError(f"Data Agent definition root not found: {DEFINITION_ROOT}")

    token = get_access_token()

    # 1. Resolve the Step-10 workspace.
    workspace_id = resolve_workspace_id(token, plan)

    # 2. Resolve the Step-14 semantic model (required grounding source).
    semantic_model_id, semantic_model_name = resolve_semantic_model(
        token, workspace_id, plan.semantic_model_name
    )

    # 3. Resolve the Step-16 ontology's auto-created Graph (optional graph source; R3/R4).
    graph: Optional[Tuple[str, str]] = None
    if plan.enable_ontology:
        graph = resolve_graph(token, workspace_id, plan.graph_name)
    else:
        LOG.info(
            "features.enable_ontology=false - grounding on the semantic model only. The graph "
            "source (the ontology's auto-created Graph, R4 §5.3) is the programmatic path to "
            "ontology-backed reasoning; attaching the ontology directly may be a UI step (R4)."
        )
    include_graph = graph is not None
    graph_id = graph[0] if graph else None
    graph_name = graph[1] if graph else None

    # 4. Build the item definition (tokens substituted; published stage mirrored; R3 §4.2/§9).
    parts = build_definition_parts(
        workspace_id=workspace_id,
        semantic_model_id=semantic_model_id,
        semantic_model_name=semantic_model_name,
        graph_id=graph_id,
        graph_name=graph_name,
        include_graph=include_graph,
    )
    definition = build_definition(parts)
    LOG.info(
        "Assembled %d definition part(s): semantic_model=%r%s.",
        len(parts), semantic_model_name,
        f" + graph={graph_name!r}" if include_graph else " (no graph source)",
    )

    # 5. Find-or-create the Data Agent item and deploy/refresh the definition (first pass:
    #    schema-valid placeholder DataSourceElement ids; binding the sources triggers
    #    Fabric to auto-generate the real element metadata).
    agent = find_or_create_data_agent(token, workspace_id, plan, definition)
    agent_id = str(agent.get("id") or "")

    # 6. Reconcile: retrieve the real DataSourceElement ids from the live agent
    #    (getDefinition; R3 line 358), inject them into the datasource parts, and re-deploy
    #    so the published definition carries real element ids instead of placeholders.
    reconciled = False
    if agent_id:
        reconciled = reconcile_datasource_elements(
            token,
            workspace_id,
            agent_id,
            semantic_model_id=semantic_model_id,
            semantic_model_name=semantic_model_name,
            graph_id=graph_id,
            graph_name=graph_name,
            include_graph=include_graph,
        )

    LOG.info(
        "Done. workspace_id=%s data_agent_id=%s sources=[semantic_model%s] elements=%s. "
        "Ask a sample question (e.g. 'average vehicle utilization across Seattle this month', "
        "'which sites have the most idle vehicles', 'top one-way flows') to validate grounding. "
        "R4: attaching the ontology directly (NL2Ontology) may be a UI step; this agent uses the "
        "graph source as the programmatic path.",
        workspace_id, agent.get("id"), ", graph" if include_graph else "",
        "real (reconciled via getDefinition)" if reconciled else "committed placeholders",
    )
    return 0


def _print_dry_run(plan: DataAgentPlan) -> int:
    """Credential-free preview of every intended REST call. No auth, no mutation."""
    LOG.info("[DRY-RUN] No authentication and no changes will be made.")
    LOG.info("[DRY-RUN] Config: %s", plan.config_path or "<none>")
    LOG.info("[DRY-RUN] enable_data_agent=%s enable_ontology=%s",
             plan.enable_data_agent, plan.enable_ontology)
    if not plan.enable_data_agent:
        LOG.info("[DRY-RUN] Feature gate off - nothing would be created.")
        return 0
    if plan.use_existing_workspace:
        LOG.info("[DRY-RUN] Would GET %s/workspaces/%s (existing).",
                 FABRIC_API_BASE, plan.existing_workspace_id)
    else:
        LOG.info("[DRY-RUN] Would GET %s/workspaces to resolve %r -> id.",
                 FABRIC_API_BASE, plan.workspace_name)
    LOG.info("[DRY-RUN] Would GET %s/workspaces/{id}/items?type=%s to resolve semantic model %r.",
             FABRIC_API_BASE, SEMANTIC_MODEL_ITEM_TYPE, plan.semantic_model_name)
    include_graph = plan.enable_ontology
    if include_graph:
        LOG.info("[DRY-RUN] Would GET %s/workspaces/{id}/items?type=%s to resolve the ontology's "
                 "auto-created Graph (name=%r or the single Graph item).",
                 FABRIC_API_BASE, GRAPH_ITEM_TYPE, plan.graph_name or "<auto>")
    else:
        LOG.info("[DRY-RUN] enable_ontology=false - graph source dropped; semantic-model only.")
    # Assemble the parts offline with placeholder ids to validate the definition structure.
    try:
        parts = build_definition_parts(
            workspace_id=ZERO_GUID,
            semantic_model_id=ZERO_GUID,
            semantic_model_name=plan.semantic_model_name,
            graph_id=ZERO_GUID if include_graph else None,
            graph_name=(plan.graph_name or "ZavaFleetOntologyGraph") if include_graph else None,
            include_graph=include_graph,
        )
        LOG.info("[DRY-RUN] Definition would have %d part(s):", len(parts))
        for part in parts:
            LOG.info("[DRY-RUN]   part: %s", part["path"])
    except DataAgentError as exc:
        LOG.warning("[DRY-RUN] could not assemble definition parts: %s", exc)
    LOG.info("[DRY-RUN] Would find-or-create Data Agent %r "
             "(POST %s/workspaces/{id}/dataAgents; InlineBase64 definition; idempotent "
             "updateDefinition on re-run).", plan.agent_name, FABRIC_API_BASE)
    LOG.info("[DRY-RUN] Would then getDefinition (POST %s/workspaces/{id}/dataAgents/{id}/"
             "getDefinition) to retrieve the real DataSourceElement ids Fabric auto-generates "
             "(R3 line 358), inject them into each datasource.json, and updateDefinition again "
             "so the published definition carries real element ids (not placeholders).",
             FABRIC_API_BASE)
    LOG.info("[DRY-RUN] Manual nuance (R4): attaching the ontology directly as an 'ontology' "
             "(NL2Ontology) source may be UI-only; the graph source is the programmatic path.")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create the Zava Fabric Data Agent (GA) grounded on the Direct Lake semantic "
                    "model (NL2DAX) and the ontology's auto-created Graph (NL2GQL); Fabric Data "
                    "Agent REST API + item definition.",
    )
    parser.add_argument(
        "--config",
        help="Path to deploy_config.json (defaults to fabric/config/deploy_config.json, then "
             "the committed .sample.json).",
    )
    parser.add_argument("--workspace-name", help="Workspace display name (overrides config/env).")
    parser.add_argument(
        "--workspace-id", dest="existing_workspace_id",
        help="Existing workspace GUID to target (overrides config/env).",
    )
    parser.add_argument(
        "--semantic-model-name",
        help="Step-14 Direct Lake semantic model display name (overrides config/env).",
    )
    parser.add_argument(
        "--graph-name",
        help="Step-16 ontology's auto-created Graph display name (overrides config/env). "
             "Omit to auto-resolve the single Graph item in the workspace.",
    )
    parser.add_argument("--agent-name", help="Data Agent display name (overrides config/env).")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print intended REST calls without authenticating or mutating anything.",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Enable debug logging.")
    return parser


def main(argv: Optional[list] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    try:
        plan = resolve_plan(
            config_path=args.config,
            workspace_name=args.workspace_name,
            existing_workspace_id=args.existing_workspace_id,
            semantic_model_name=args.semantic_model_name,
            graph_name=args.graph_name,
            agent_name=args.agent_name,
        )
        return run(plan, dry_run=args.dry_run)
    except DataAgentError as exc:
        LOG.error("%s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
